//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalPlacementStudent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YeuditTablePlaceMentEntities : DbContext
    {
        public YeuditTablePlaceMentEntities()
            : base("name=YeuditTablePlaceMentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassTbl> ClassTbl { get; set; }
        public virtual DbSet<StudentTbl> StudentTbl { get; set; }
        public virtual DbSet<TypicalTbl> TypicalTbl { get; set; }
        public virtual DbSet<TypicalToStudentTbl> TypicalToStudentTbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypicalToStudent_Tbl> TypicalToStudent_Tbl { get; set; }
    }
}
