//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalPlacementStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypicalTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypicalTbl()
        {
            this.TypicalToStudentTbl = new HashSet<TypicalToStudentTbl>();
            this.TypicalToStudent_Tbl = new HashSet<TypicalToStudent_Tbl>();
        }
    
        public int TypicalID { get; set; }
        public string DetailTypical { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypicalToStudentTbl> TypicalToStudentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypicalToStudent_Tbl> TypicalToStudent_Tbl { get; set; }
    }
}
