//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalPlacementStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypicalToStudent_Tbl
    {
        public int TypicalToStudentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TypicalID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual StudentTbl StudentTbl { get; set; }
        public virtual TypicalTbl TypicalTbl { get; set; }
    }
}
